#!/usr/bin/env bash
set -euo pipefail

# Usage: ./scripts/set-forced-time.sh HH:MM[:SS]
# To disable forced time, pass "off" (or remove the file's contents manually).

OUT="src/c/forced_time.c"

if [[ ${1-} == "" ]]; then
  echo "Usage: $0 HH:MM[:SS]  (or 'off' to disable forced time)"
  exit 1
fi

if [[ "$1" == "off" ]]; then
  echo "Disabling forced time: restoring default (hour = -1)"
  cat > "$OUT" <<'C_EOF'
// Simple place to hardcode a forced time for screenshots.
// Edit the values below to choose the time displayed by the app.

#include "forced_time.h"

// Default: hour = -1 means no forced time.
struct tm forced_time = {
  .tm_sec = 0,
  .tm_min = 0,
  .tm_hour = -1,
};

bool forced_time_is_set(void) {
  return forced_time.tm_hour >= 0;
}

C_EOF
  echo "Wrote $OUT (backup at $BACKUP)"
  exit 0
fi

TIME="$1"
# Parse HH:MM[:SS]
if [[ ! "$TIME" =~ ^([0-9]{1,2}):([0-9]{2})(:([0-9]{2}))?$ ]]; then
  echo "Time must be HH:MM or HH:MM:SS"
  exit 1
fi
HH=${BASH_REMATCH[1]}
MM=${BASH_REMATCH[2]}
SS=${BASH_REMATCH[4]:-0}

# Normalize values to integers
HH=$((10#$HH))
MM=$((10#$MM))
SS=$((10#$SS))

if (( HH < 0 || HH > 23 || MM < 0 || MM > 59 || SS < 0 || SS > 59 )); then
  echo "Invalid time values"
  exit 1
fi

  mkdir -p "$(dirname "$OUT")"

cat > "$OUT" <<C_EOF
// Simple place to hardcode a forced time for screenshots.
// Generated by scripts/set-forced-time.sh

#include "forced_time.h"

// Forced time set by script
struct tm forced_time = {
  .tm_sec = ${SS},
  .tm_min = ${MM},
  .tm_hour = ${HH},
};

bool forced_time_is_set(void) {
  return forced_time.tm_hour >= 0;
}

C_EOF

echo "Wrote $OUT -> ${HH}:${MM}:${SS}"
