#!/usr/bin/env python3
"""Generate src/c/digit_paths.h from Fontra glyph JSON files."""

import json
import os

GLYPH_NAMES = ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine"]
FONTRA_GLYPHS = os.path.expanduser("~/fonts/fwc26/Untitled.fontra/glyphs")
OUT_H = os.path.join(os.path.dirname(os.path.abspath(__file__)), "src/c/digit_paths.h")
LAYER = "Regular"

# Fontra PointType values (fontra.core.classes.PointType)
ON_CURVE        = 0
ON_CURVE_SMOOTH = 8
OFF_CURVE_CUBIC = 2

FONT_HEIGHT = 750   # matches SVG viewBox height and font ascender
TOL = 0.4           # bezier flatness tolerance in units (sub-pixel at target sizes)


def flip_y(y):
    return FONT_HEIGHT - y


def _subdiv(p0, p1, p2, p3, result, tol2, depth=0):
    if depth > 14:
        result.append(p3); return
    cx, cy = p3[0] - p0[0], p3[1] - p0[1]
    d1 = abs((p1[0] - p0[0]) * cy - (p1[1] - p0[1]) * cx)
    d2 = abs((p2[0] - p0[0]) * cy - (p2[1] - p0[1]) * cx)
    chord2 = cx * cx + cy * cy + 1
    if (d1 + d2) ** 2 <= tol2 * chord2:
        result.append(p3); return
    m01  = ((p0[0] + p1[0]) * .5, (p0[1] + p1[1]) * .5)
    m12  = ((p1[0] + p2[0]) * .5, (p1[1] + p2[1]) * .5)
    m23  = ((p2[0] + p3[0]) * .5, (p2[1] + p3[1]) * .5)
    m012 = ((m01[0] + m12[0]) * .5, (m01[1] + m12[1]) * .5)
    m123 = ((m12[0] + m23[0]) * .5, (m12[1] + m23[1]) * .5)
    mid  = ((m012[0] + m123[0]) * .5, (m012[1] + m123[1]) * .5)
    _subdiv(p0, m01, m012, mid, result, tol2, depth + 1)
    _subdiv(mid, m123, m23, p3, result, tol2, depth + 1)


def flatten_cubic(p0, p1, p2, p3):
    result = []
    _subdiv(p0, p1, p2, p3, result, (TOL * 16) ** 2)
    return result


def is_on_curve(t):
    return t in (ON_CURVE, ON_CURVE_SMOOTH)


def process_contour(coords, types):
    """
    Convert a single Fontra contour (font-space, Y-up) to a polygon
    in SVG space (Y-down, x in [0,1000], y in [0,750]).

    coords: list of (x, y) in font space
    types:  list of point type ints, same length

    Returns list of (int, int) polygon points.
    The closing segment back to the first point is implicit (GPath handles it).
    """
    n = len(types)
    pts = [(x, flip_y(y)) for x, y in coords]

    # Find first on-curve point
    start_idx = next((i for i in range(n) if is_on_curve(types[i])), 0)

    result = [pts[start_idx]]
    i = start_idx
    steps = 0

    while steps < n:
        next_i = (i + 1) % n
        if next_i == start_idx:
            break

        if is_on_curve(types[next_i]):
            result.append(pts[next_i])
            i = next_i
            steps += 1
        else:
            # Cubic bezier: 2 off-curve control points then an on-curve endpoint
            cp1_i = next_i
            cp2_i = (cp1_i + 1) % n
            end_i  = (cp2_i + 1) % n
            for fp in flatten_cubic(pts[i], pts[cp1_i], pts[cp2_i], pts[end_i]):
                result.append(fp)
            i = end_i
            steps += 3

    # Dedup consecutive identical points
    out = [result[0]]
    for p in result[1:]:
        if abs(p[0] - out[-1][0]) > 0.3 or abs(p[1] - out[-1][1]) > 0.3:
            out.append(p)

    return [(round(x), round(y)) for x, y in out]


def glyph_to_points(glyph_json):
    path = glyph_json["layers"][LAYER]["glyph"]["path"]
    raw_coords = path["coordinates"]
    types      = path["pointTypes"]
    contours   = path["contourInfo"]

    all_pts = []
    ci_start = 0
    for ci in contours:
        ci_end = ci["endPoint"] + 1
        coords = [(raw_coords[i * 2], raw_coords[i * 2 + 1]) for i in range(ci_start, ci_end)]
        ctypes = types[ci_start:ci_end]
        all_pts.extend(process_contour(coords, ctypes))
        ci_start = ci_end

    return all_pts


def main():
    all_pts = []
    for name in GLYPH_NAMES:
        with open(os.path.join(FONTRA_GLYPHS, f"{name}.json")) as f:
            glyph = json.load(f)
        pts = glyph_to_points(glyph)
        all_pts.append(pts)
        print(f"  {name}: {len(pts)} pts")

    max_pts = max(len(p) for p in all_pts)
    print(f"  max: {max_pts} pts")

    lines = [
        "#pragma once",
        "#include <pebble.h>",
        "",
        "// Digit path points in SVG space: x in [0,1000], y in [0,750].",
        "// Draw-time scaling: pt.x * rect.w / 1000 + origin.x  (same for y/750)",
        "// Generated by fontra_to_c.py -- do not edit.",
        "",
    ]

    for d, pts in enumerate(all_pts):
        n = len(pts)
        rows = []
        for i in range(0, n, 4):
            chunk = pts[i:i + 4]
            rows.append("  " + ", ".join(f"{{{x},{y}}}" for x, y in chunk))
        lines.append(f"static const GPoint kDigitPts{d}[{n}] = {{")
        lines.append(",\n".join(rows))
        lines.append("};")
        lines.append("")

    lines += [
        "typedef struct { uint16_t n; const GPoint *pts; } DigitPath;",
        "",
        "static const DigitPath kDigitPaths[10] = {",
    ]
    for d, pts in enumerate(all_pts):
        lines.append(f"  {{ {len(pts)}, kDigitPts{d} }},")
    lines += [
        "};",
        "",
        f"#define DIGIT_PATH_MAX_PTS  {max_pts + 8}",
    ]

    with open(OUT_H, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"  written: {OUT_H}")


if __name__ == "__main__":
    main()
